# ================================================================================================
# !!!!!请务必先看此条提示!!!!!：
# 由于本地开发时使用单体启动最方便，因此配置文件目前临时改名为application-xx.properties，并放在resources目录下。
# 正式发布时会改回application.properties，并放在resources/config目录下。
# ================================================================================================

#Mon Dec 15 06:06:45 UTC 2025
micronaut.application.name=kot-common-api
