-- PostgreSQL member user table
create table if not exists member_users (
    id bigint generated by default as identity primary key,
    username varchar(32) not null,
    mobile varchar(32),
    password_hash varchar(255) not null,
    nickname varchar(128) not null,
    email varchar(64),
    avatar_url varchar(1024),
    status smallint not null default 1 check (status in (0, 1)),
    login_ip inet,
    login_time timestamp with time zone,
    creator_id bigint,
    create_time timestamp with time zone not null default current_timestamp,
    updater_id bigint,
    update_time timestamp with time zone not null default current_timestamp,
    deleted boolean not null default false,
    tenant_id bigint not null default 0,
    constraint uk_member_users_tenant_username unique (tenant_id, username),
    constraint uk_member_users_tenant_mobile unique (tenant_id, mobile),
    constraint ck_member_users_username check (username = btrim(username) and username ~ '^[A-Za-z][A-Za-z0-9_]{2,31}$')
);

comment on table member_users is 'C端会员用户表';
comment on column member_users.tenant_id is '租户 ID';
create index if not exists idx_member_users_login on member_users (username) where deleted = false;
create index if not exists idx_member_users_mobile_login on member_users (mobile) where deleted = false;
