apiVersion: v1
kind: ConfigMap
metadata:
  name: kot-server-config
data:
  application-dev.yml: |
    micronaut:
      application:
        name: kot-server
      server:
        port: 8080
    r2dbc:
      datasources:
        default:
          url: r2dbc:pool:postgresql://localhost:5432/kot_cloud_dev
          username: dev_user
          password: dev_pass
