apiVersion: v1
kind: ConfigMap
metadata:
  name: kot-server-config
data:
  application-prod.yml: |
    micronaut:
      application:
        name: kot-server
      server:
        port: 8080
    datasources:
      default:
        url: jdbc:postgresql://postgres-service:5432/kot_cloud
        driver-class-name: org.postgresql.Driver
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
