[versions]
ktor = "3.3.3"
micrometer = "1.14.0"
exposed = "1.0.0-rc-4"
koin = "4.1.1"
logback = "1.5.22"
koter = "0.0.1"

# Micronaut 相关版本
# TODO WhiteSprite：鉴于 micronaut 即将发布5.0.0版本，暂不使用 Micronaut 5.0 的不稳定版本
micronaut = "4.10.11"
micronaut-validation = "4.12.0"
micronaut-data  = "4.14.2"
micronaut-jdbc = "7.0.0"

# DB
postgre = "42.7.8"

[libraries]
# Ktor核心
ktor-server-core = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }

# 数据库
exposed-core = { group = "org.jetbrains.exposed", name = "exposed-core", version.ref = "exposed" }
exposed-jdbc = { group = "org.jetbrains.exposed", name = "exposed-jdbc", version.ref = "exposed" }
exposed-java-time = { group = "org.jetbrains.exposed", name = "exposed-java-time", version.ref = "exposed" }

# 监控
micrometer-core = { group = "io.micrometer", name = "micrometer-core", version.ref = "micrometer" }
micrometer-registry-prometheus = { group = "io.micrometer", name = "micrometer-registry-prometheus", version.ref = "micrometer" }

# 依赖注入
koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-ktor = { group = "io.insert-koin", name = "koin-ktor", version.ref = "koin" }

# 日志
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

# Micronaut 框架
micronaut-core = { group = "io.micronaut", name = "micronaut-core", version.ref = "micronaut" }
micronaut-http-client = { group = "io.micronaut", name = "micronaut-http-client", version.ref = "micronaut" }
micronaut-http = { group = "io.micronaut", name = "micronaut-http", version.ref = "micronaut" }
micronaut-logging = { group = "io.micronaut", name = "micronaut-logging", version.ref = "micronaut" }
micronaut-context = { group = "io.micronaut", name = "micronaut-context", version.ref = "micronaut" }
micronaut-validation = { group = "io.micronaut.validation", name = "micronaut-validation", version.ref = "micronaut-validation" }
micronaut-validation-annotations = { group = "io.micronaut.validation", name = "micronaut-validation-annotations", version.ref = "micronaut" }
micronaut-test-junit5 = { group = "io.micronaut.test", name = "micronaut-test-junit5", version.ref = "micronaut" }

# Micronaut Data 框架
micronaut-data-runtime = { group = "io.micronaut.data", name = "micronaut-data-runtime", version.ref = "micronaut-data" }
micronaut-data-processor = { group = "io.micronaut.data", name = "micronaut-data-processor", version.ref = "micronaut-data" }
micronaut-data-jdbc = { group = "io.micronaut.data", name = "micronaut-data-jdbc", version.ref = "micronaut-data" }
micronaut-data-tx = { group = "io.micronaut.data", name = "micronaut-data-tx", version.ref = "micronaut-data" }
# Hikari 连接池
micronaut-jdbc-hikari = { group = "io.micronaut.sql", name = "micronaut-jdbc-hikari", version.ref = "micronaut-jdbc" }

# Maria DB 驱动

# PostgreSQL 驱动
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgre" }

