micronaut:
  server:
    port: 8002

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/kot_cloud
    username: root
    password: 123456
    maximumPoolSize: 5

logger:
  levels:
    root: DEBUG
    com.whitesprite.dev.module.system: DEBUG