# Member module anonymous endpoints. Other member APIs remain protected by @Secured("USER").
micronaut.security.intercept-url-map[9].pattern=/v1/api/auth/login
micronaut.security.intercept-url-map[9].http-method=POST
micronaut.security.intercept-url-map[9].access[0]=isAnonymous()
micronaut.security.intercept-url-map[10].pattern=/v1/api/auth/register-by-username
micronaut.security.intercept-url-map[10].http-method=POST
micronaut.security.intercept-url-map[10].access[0]=isAnonymous()
micronaut.security.intercept-url-map[11].pattern=/v1/api/auth/register-by-mobile
micronaut.security.intercept-url-map[11].http-method=POST
micronaut.security.intercept-url-map[11].access[0]=isAnonymous()
