-- Name: sql\kot_cloud_system.sql
-- DB: PostgreSQL 18.1
-- Author: WhiteSprite
-- Date: 2025-12-27 02:51:09
-- Description: 结构SQL文件

-- 系统用户表
drop table if exists system_users;
create table system_users
(
    id            bigint generated by default as identity
        constraint pk_system_users
            primary key,
    username      varchar(128)                                       not null
        constraint ck_system_users_username_format
            check (((length((username)::text) >= 3) AND (length((username)::text) <= 32)) AND
                   ((username)::text = btrim((username)::text)) AND ((username)::text ~ '^[A-Za-z0-9_]+$'::text)),
    password_hash varchar(255)                                       not null,
    nickname      varchar(128),
    dept_id       bigint,
    email         varchar(64),
    mobile        varchar(32),
    gender        smallint                 default 0,
    avatar_url    varchar(1024),
    status        smallint                 default 0                 not null,
    login_ip      inet,
    remark        varchar(256),
    creator_id    bigint,
    create_time   timestamp with time zone default CURRENT_TIMESTAMP not null,
    updater_id    bigint,
    update_time   timestamp with time zone default CURRENT_TIMESTAMP not null,
    deleted       boolean                  default false             not null,
    tenant_id     bigint                   default 0                 not null,
    login_time    timestamp,
    constraint uk_system_users_tenant_username
        unique (tenant_id, username)
);

comment on table system_users is '系统用户表';

comment on column system_users.id is '主键';

comment on constraint pk_system_users on system_users is '主键';

comment on column system_users.username is '用户名';

comment on constraint ck_system_users_username_format on system_users is '用户名检查';

comment on column system_users.password_hash is '密码哈希';

comment on column system_users.nickname is '昵称';

comment on column system_users.dept_id is '部门Id';

comment on column system_users.email is '邮箱';

comment on column system_users.mobile is '手机号';

comment on column system_users.gender is '性别';

comment on column system_users.avatar_url is '头像地址';

comment on column system_users.status is '状态';

comment on column system_users.login_ip is '登录IP，理论应兼容IPv6';

comment on column system_users.remark is '备注';

comment on column system_users.creator_id is '创建人Id';

comment on column system_users.create_time is '创建时间';

comment on column system_users.updater_id is '更新人Id';

comment on column system_users.update_time is '更新时间';

comment on column system_users.deleted is '是否删除';

comment on column system_users.tenant_id is '租户Id';

comment on column system_users.login_time is '最后登陆时间';

comment on constraint uk_system_users_tenant_username on system_users is '用户名-租户约束';

alter table system_users
    owner to rootpg;



-- 登录日志表
-- Name: sql\kot_cloud_system.sql
drop table if exists system_login_log;
create table system_login_log
(
    id          bigint generated by default as identity
        constraint pk_system_login_log
            primary key,
    log_type    integer                                    not null,
    trace_id    varchar(64)  default ''::character varying,
    user_id     bigint       default 0                     not null,
    user_type   smallint     default 0                     not null,
    username    varchar(128) default ''::character varying not null,
    result      smallint                                   not null,
    fail_reason varchar(256),
    user_ip     inet,
    user_agent  varchar(512) default ''::character varying not null,
    session_id  varchar(64),
    create_time timestamp    default CURRENT_TIMESTAMP     not null,
    tenant_id   bigint       default 0                     not null,
    creator_id  bigint,
    updater_id  bigint,
    update_time timestamp    default CURRENT_TIMESTAMP     not null,
    deleted     boolean      default false                 not null
);

comment on column system_login_log.id is '主键';

comment on column system_login_log.log_type is '日志类型';

comment on column system_login_log.trace_id is '链路追踪Id';

comment on column system_login_log.user_id is '用户ID';

comment on column system_login_log.user_type is '用户类型';

comment on column system_login_log.username is '用户名';

comment on column system_login_log.result is '登陆结果。参考源码LoginResultEnum';

comment on column system_login_log.fail_reason is '失败原因';

comment on column system_login_log.user_ip is '用户IP';

comment on column system_login_log.user_agent is '浏览器UA';

comment on column system_login_log.session_id is '会话Id';

comment on column system_login_log.create_time is '创建时间';

comment on column system_login_log.tenant_id is '租户ID';

comment on column system_login_log.creator_id is '创建者ID';

comment on column system_login_log.updater_id is '更新者ID';

comment on column system_login_log.update_time is '更新时间';

comment on column system_login_log.deleted is '是否删除';

alter table system_login_log
    owner to rootpg;

create index idx_system_login_log_username
    on system_login_log (username);

create index idx_system_login_log_create_time
    on system_login_log (create_time desc);

create index idx_system_login_log_user_id
    on system_login_log (user_id);

create index idx_system_login_log_trace_id
    on system_login_log (trace_id);

create index idx_system_login_log_session_id
    on system_login_log (session_id);



-- RBAC roles. super_admin is inserted and maintained manually by database operators.
create table system_role
(
    id              bigint generated by default as identity primary key,
    code            varchar(128)                          not null,
    name            varchar(128)                          not null,
    status          smallint    default 0                 not null,
    built_in        boolean     default false             not null,
    data_scope_type varchar(32) default 'ALL'::varchar    not null,
    remark          varchar(256),
    creator_id      bigint,
    create_time     timestamp   default CURRENT_TIMESTAMP not null,
    updater_id      bigint,
    update_time     timestamp   default CURRENT_TIMESTAMP not null,
    deleted         boolean     default false             not null,
    tenant_id       bigint      default 0                 not null,
    constraint uk_system_role_tenant_code unique (tenant_id, code)
);

create table system_permission
(
    id          bigint generated by default as identity primary key,
    code        varchar(128)                            not null,
    name        varchar(128)                            not null,
    resource    varchar(128)                            not null,
    action      varchar(64)                             not null,
    type        varchar(32) default 'FUNCTION'::varchar not null,
    status      smallint    default 0                   not null,
    remark      varchar(256),
    creator_id  bigint,
    create_time timestamp   default CURRENT_TIMESTAMP   not null,
    updater_id  bigint,
    update_time timestamp   default CURRENT_TIMESTAMP   not null,
    deleted     boolean     default false               not null,
    tenant_id   bigint      default 0                   not null,
    constraint uk_system_permission_tenant_code unique (tenant_id, code)
);

create table system_menu
(
    id              bigint generated by default as identity primary key,
    code            varchar(128)                        not null,
    parent_code     varchar(128),
    title           varchar(128)                        not null,
    type            varchar(32)                         not null,
    path            varchar(1024),
    icon            varchar(128),
    sort            integer   default 0                 not null,
    visible         boolean   default true              not null,
    permission_code varchar(128),
    remark          varchar(256),
    creator_id      bigint,
    create_time     timestamp default CURRENT_TIMESTAMP not null,
    updater_id      bigint,
    update_time     timestamp default CURRENT_TIMESTAMP not null,
    deleted         boolean   default false             not null,
    tenant_id       bigint    default 0                 not null,
    constraint uk_system_menu_tenant_code unique (tenant_id, code)
);

create index idx_system_menu_tenant_parent_sort
    on system_menu (tenant_id, parent_code, sort);

create table system_user_role
(
    id        bigint generated by default as identity primary key,
    user_id   bigint default 0 not null,
    role_id   bigint default 0 not null,
    tenant_id bigint default 0 not null,
    constraint uk_system_user_role unique (tenant_id, user_id, role_id)
);

create index idx_system_user_role_tenant_user
    on system_user_role (tenant_id, user_id);

create table system_role_permission
(
    id            bigint generated by default as identity primary key,
    role_id       bigint default 0 not null,
    permission_id bigint default 0 not null,
    tenant_id     bigint default 0 not null,
    constraint uk_system_role_permission unique (tenant_id, role_id, permission_id)
);

create index idx_system_role_permission_tenant_role
    on system_role_permission (tenant_id, role_id);

-- Bootstrap roles and permissions. super_admin assignment is intentionally omitted.
insert into system_role (code, name, status, built_in, data_scope_type, remark, tenant_id)
values ('super_admin', '平台超级管理员', 0, true, 'ALL', '仅允许数据库运维手工分配', 0),
       ('system_admin', '系统管理员', 0, true, 'ALL', '公开注册管理员默认角色，可在角色管理中调整权限', 0)
on conflict (tenant_id, code) do nothing;

insert into system_permission (code, name, resource, action, type, status, tenant_id)
values ('system:user:list', '查看用户', 'system.user', 'list', 'FUNCTION', 0, 0),
       ('system:user:create', '创建用户', 'system.user', 'create', 'FUNCTION', 0, 0),
       ('system:user:update', '更新用户', 'system.user', 'update', 'FUNCTION', 0, 0),
       ('system:user:delete', '删除用户', 'system.user', 'delete', 'FUNCTION', 0, 0),
       ('system:role:list', '查看角色', 'system.role', 'list', 'FUNCTION', 0, 0),
       ('system:role:create', '创建角色', 'system.role', 'create', 'FUNCTION', 0, 0),
       ('system:role:update', '更新角色', 'system.role', 'update', 'FUNCTION', 0, 0),
       ('system:role:delete', '删除角色', 'system.role', 'delete', 'FUNCTION', 0, 0),
       ('system:menu:list', '查看菜单', 'system.menu', 'list', 'FUNCTION', 0, 0),
       ('system:menu:create', '创建菜单', 'system.menu', 'create', 'FUNCTION', 0, 0),
       ('system:menu:update', '更新菜单', 'system.menu', 'update', 'FUNCTION', 0, 0),
       ('system:menu:delete', '删除菜单', 'system.menu', 'delete', 'FUNCTION', 0, 0)
on conflict (tenant_id, code) do nothing;

insert into system_role_permission (role_id, permission_id, tenant_id)
select r.id, p.id, r.tenant_id
from system_role r
         join system_permission p on p.tenant_id = r.tenant_id
where r.code = 'system_admin'
  and r.tenant_id = 0
on conflict (tenant_id, role_id, permission_id) do nothing;

