-- Name: sql\kot_cloud_system.sql
-- DB: PostgreSQL 18.1
-- Author: WhiteSprite
-- Date: 2025-12-27 02:51:09
-- Description: 结构SQL文件

-- 系统用户表
drop table if exists system_users;
create table system_users
(
    id            bigint generated by default as identity
        constraint pk_system_users
            primary key,
    username      varchar(128)                        not null
        constraint ck_system_users_username_format
            check (((length((username)::text) >= 3) AND (length((username)::text) <= 32)) AND
                   ((username)::text = btrim((username)::text)) AND ((username)::text ~ '^[A-Za-z0-9_]+$'::text)),
    password_hash varchar(255)                        not null,
    nickname      varchar(128),
    dept_id       bigint,
    email         varchar(64),
    mobile        varchar(32),
    gender        smallint  default 0,
    avatar_url    varchar(1024),
    status        smallint  default 0                 not null,
    login_ip      inet,
    remark        varchar(256),
    creator_id    bigint,
    create_time   timestamp default CURRENT_TIMESTAMP not null,
    updater_id    bigint,
    update_time   timestamp default CURRENT_TIMESTAMP not null,
    deleted       boolean   default false             not null,
    tenant_id     bigint    default 0                 not null,
    constraint uk_system_users_tenant_username
        unique (tenant_id, username)
);

comment on table system_users is '系统用户表';

comment on column system_users.id is '主键';

comment on constraint pk_system_users on system_users is '主键';

comment on column system_users.username is '用户名';

comment on constraint ck_system_users_username_format on system_users is '用户名检查';

comment on column system_users.password_hash is '密码哈希';

comment on column system_users.nickname is '昵称';

comment on column system_users.dept_id is '部门Id';

comment on column system_users.email is '邮箱';

comment on column system_users.mobile is '手机号';

comment on column system_users.gender is '性别';

comment on column system_users.avatar_url is '头像地址';

comment on column system_users.status is '状态';

comment on column system_users.login_ip is '登录IP，理论应兼容IPv6';

comment on column system_users.remark is '备注';

comment on column system_users.creator_id is '创建人Id';

comment on column system_users.create_time is '创建时间';

comment on column system_users.updater_id is '更新人Id';

comment on column system_users.update_time is '更新时间';

comment on column system_users.deleted is '是否删除';

comment on column system_users.tenant_id is '租户Id';

comment on constraint uk_system_users_tenant_username on system_users is '用户名-租户约束';

alter table system_users
    owner to user_rmtxsa;

